/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CheckInWithResponse {
  'checkIn' : EmotionalCheckIn,
  'response' : SupportiveResponse,
}
export interface EmotionalCheckIn {
  'feelings' : string,
  'content' : string,
  'timestamp' : Time,
}
export interface EmpatheticStory {
  'title' : string,
  'content' : string,
  'relatedFeeling' : string,
}
export interface FollowUpPrompt {
  'message' : string,
  'options' : Array<string>,
}
export interface JournalEntry {
  'methodType' : string,
  'content' : string,
  'userId' : Principal,
  'moodTag' : [] | [string],
  'timestamp' : Time,
}
export interface SupportiveResponse {
  'followUpQuestion' : string,
  'mainMessage' : string,
  'relatableStory' : string,
  'actionOptions' : Array<string>,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCheckIn' : ActorMethod<[string, string], CheckInWithResponse>,
  'addEmpatheticStory' : ActorMethod<[EmpatheticStory], undefined>,
  'addFollowUpPrompt' : ActorMethod<[FollowUpPrompt], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearJournalEntries' : ActorMethod<[], undefined>,
  'getAllCheckIns' : ActorMethod<[], Array<EmotionalCheckIn>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getRandomFollowUpPrompt' : ActorMethod<[], [] | [FollowUpPrompt]>,
  'getUserCheckIns' : ActorMethod<[Principal], Array<EmotionalCheckIn>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasCheckIns' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveJournalEntry' : ActorMethod<[string, string, [] | [string]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];