/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const EmotionalCheckIn = IDL.Record({
  'feelings' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : Time,
});
export const SupportiveResponse = IDL.Record({
  'followUpQuestion' : IDL.Text,
  'mainMessage' : IDL.Text,
  'relatableStory' : IDL.Text,
  'actionOptions' : IDL.Vec(IDL.Text),
});
export const CheckInWithResponse = IDL.Record({
  'checkIn' : EmotionalCheckIn,
  'response' : SupportiveResponse,
});
export const EmpatheticStory = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'relatedFeeling' : IDL.Text,
});
export const FollowUpPrompt = IDL.Record({
  'message' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const JournalEntry = IDL.Record({
  'methodType' : IDL.Text,
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'moodTag' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCheckIn' : IDL.Func([IDL.Text, IDL.Text], [CheckInWithResponse], []),
  'addEmpatheticStory' : IDL.Func([EmpatheticStory], [], []),
  'addFollowUpPrompt' : IDL.Func([FollowUpPrompt], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearJournalEntries' : IDL.Func([], [], []),
  'getAllCheckIns' : IDL.Func([], [IDL.Vec(EmotionalCheckIn)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getRandomFollowUpPrompt' : IDL.Func(
      [],
      [IDL.Opt(FollowUpPrompt)],
      ['query'],
    ),
  'getUserCheckIns' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EmotionalCheckIn)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasCheckIns' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveJournalEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const EmotionalCheckIn = IDL.Record({
    'feelings' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : Time,
  });
  const SupportiveResponse = IDL.Record({
    'followUpQuestion' : IDL.Text,
    'mainMessage' : IDL.Text,
    'relatableStory' : IDL.Text,
    'actionOptions' : IDL.Vec(IDL.Text),
  });
  const CheckInWithResponse = IDL.Record({
    'checkIn' : EmotionalCheckIn,
    'response' : SupportiveResponse,
  });
  const EmpatheticStory = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'relatedFeeling' : IDL.Text,
  });
  const FollowUpPrompt = IDL.Record({
    'message' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const JournalEntry = IDL.Record({
    'methodType' : IDL.Text,
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'moodTag' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCheckIn' : IDL.Func([IDL.Text, IDL.Text], [CheckInWithResponse], []),
    'addEmpatheticStory' : IDL.Func([EmpatheticStory], [], []),
    'addFollowUpPrompt' : IDL.Func([FollowUpPrompt], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearJournalEntries' : IDL.Func([], [], []),
    'getAllCheckIns' : IDL.Func([], [IDL.Vec(EmotionalCheckIn)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getRandomFollowUpPrompt' : IDL.Func(
        [],
        [IDL.Opt(FollowUpPrompt)],
        ['query'],
      ),
    'getUserCheckIns' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EmotionalCheckIn)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasCheckIns' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveJournalEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };